---
title: BondMemosBookATWSR
author: Shiwz11
date: '2021-07-07'
slug: bondmemosbookatwsr
categories:
  - Memos
tags:
  - Bonds
---

# 写在前面

该笔记来自于：
Algorithmic Trading Winning Strategies and Their Rationale

by:Ernest P. Chan


# Backtesting and Automated Execution

回测和自动化执行

市面上大部分公开的策略都不会对策略的细节进行详细说明，而这些细节会对策略的盈利能力造成巨大影响，因此，回测策略并找出最优参数就成为了必要。而且，回测有助于发现策略中隐藏的缺陷。

## 回测中常见的错误

### 前视性偏误

Look-ahead bias : 顾名思义，说的是，你的回测程序使用了未来的（明天的）交易价格来决定当前的（今天的）交易价格。一种常见的前视性偏误是在回测中，使用某日的价格高点或低点来决定策略的进入信号。实际上，在该交易日完结之前，我们无法知道该交易日的实际价格高点和低点。这种偏误属于简单的变成上的失误。

### 数据透视偏差和线性模型的妙处

类似于数据过拟合，当你使用了过多的的参数来拟合某段时间特定的市场模式时，虽然拟合效果可能会很好，但是，这种特殊的市场模式在未来很可能不会再出现，就造成了其样本外预测效力极差。这称之为数据透视偏差。

诊断这种偏误的方法也很简单，就是使用样本外数据对模型的预测效果进行评价，但时不幸的是，当模型样本外预测能力表现较差的时候，你真的有决心舍弃之前所有的工作，重新拟合模型吗。恐怕不是，我们可能会针对模型做出这样或那样的改变来使其样本外预测能力和样本内预测能力都说的过去，而实际来看，当你这么做的时候，你实际上是把样本外数据当作样本外数据来用了，这就违反了科学性。

更好的办法是，**交叉验证**。一般来说，非线性模型相比于线性模型会有更多的参数，也有更大的可能引致过拟合。为了避免这种错误，我们通常选择遵循奥卡姆剃刀原则，选择尽可能少的参数。

另一个重要的问题是对分布的假设，我们根据经验知道，正太分布通常并不能很好的描述实际金融数据，但是根据奥卡姆剃刀原则，除非你有强有力的证据表明，应当使用其他分布，那么，你就应该使用最简单的正态分布。

线性模型好就好在它简单，简单并不意味着无效。线性模型生效大多数时候是因为其抓住了市场失灵这一事实。

Daniel Kahneman , the Nobel Prize-winning economist, wrote in hist bestseller *Thinking, Fast and Slow*





